name = "cre-finder-ai"
compatibility_date = "2024-08-21"
pages_build_output_dir = ".next"

[env.production]
name = "cre-finder-ai"

[env.production.vars]
NODE_ENV = "production"

# Environment variables will be set via Cloudflare dashboard
# Required environment variables:
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY  
# SUPABASE_SERVICE_KEY
# NEXT_PUBLIC_APP_URL
# NEXT_PUBLIC_MARKETING_URL
# TWILIO_ACCOUNT_SID
# TWILIO_AUTH_TOKEN
# TWILIO_PHONE_NUMBER
# TWILIO_SMS_WEBHOOK_URL
# TWILIO_VOICE_WEBHOOK_URL
# SENDGRID_API_KEY
# VAPI_API_KEY
# VAPI_WEBHOOK_SECRET
# NEXT_PUBLIC_VAPI_PUBLIC_KEY
